In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read the survey data from the Richmond market

In [3]:
df = pd.read_excel('./Segmentation at Sticks Kebob Shop.xlsx', sheet_name = None)

In [4]:
df

OrderedDict([('Title Page',
                                                        Unnamed: 0  \
              0                                                NaN
              1                                                NaN
              2  This spreadsheet was prepared by Rajkumar Venk...
              3                                      Sept. 4, 2015

                                                        Unnamed: 1
              0  This spreadsheet supports STUDENT analysis of ...
              1                                                NaN
              2                                                NaN
              3                                                NaN  ),
             ('Sheet1',
                   Obs  Customer  I tend to plan things very carefully.  \
              0      2         0                                      1
              1      3         0                                      1
              2      4         0                                      2
              3      5         0                                      2
              4     10         0                                      2
              ..   ...       ...                                    ...
              390  478         1                                      3
              391  479         1                                      2
              392  480         1                                      1
              393  481         1                                      1
              394  482         1                                      1

                   I sometimes have trouble controlling my spending.  \
              0                                                    2
              1                                                    3
              2                                                    4
              3                                                    4
              4                                                    4
              ..                                                 ...
              390                                                  3
              391                                                  2
              392                                                  4
              393                                                  4
              394                                                  3

                   I think it is important to purchase products that are made locally.  \
              0                                                  3.0
              1                                                  3.0
              2                                                  3.0
              3                                                  1.0
              4                                                  2.0
              ..                                                 ...
              390                                                2.0
              391                                                2.0
              392                                                1.0
              393                                                1.0
              394                                                2.0

                   I carefully consider the health benefits of what I eat.  Segment
              0                                                    2            1.0
              1                                                    2            1.0
              2                                                    2            2.0
              3                                                    2            5.0
              4                                                    3            2.0
              ..                                                 ...            ...
              390                                                  2            3.0
              391                                                  2            4.0
              392                                                  2            2.0
              393                                                  1            3.0
              394                                                  2            3.0

              [395 rows x 7 columns]),
             ('Additional Demo Codes',
                 Unnamed: 0                                         Unnamed: 1
              0         NaN                       Gender: 1 = Female, 2 = Male
              1         NaN                                                NaN
              2         NaN    Age: Under 25 = 0, 26–40= 2, 41–65 = 3, 65+ = 4
              3         NaN                                                NaN
              4         NaN  Income: Under $50,000 = 1, $50,000–$100,000 = ...
              5         NaN                                                NaN
              6         NaN  Household Type: Single = 1, Family = 2, Other = 3),
             ('Customer Survey',
                   obs  \
              0    292
              1    306
              2    314
              3    332
              4    346
              ..   ...
              197  448
              198  460
              199  461
              200  462
              201  468

                   How many times in the last week did you do the following? - Make and eat lunch at home  \
              0                                                  1.0
              1                                                  1.0
              2                                                  NaN
              3                                                  3.0
              4                                                  4.0
              ..                                                 ...
              197                                                4.0
              198                                                1.0
              199                                                4.0
              200                                                2.0
              201                                                6.0

                   How many times in the last week did you do the following? - Bring own lunch to work  \
              0                                                  3.0
              1                                                  1.0
              2                                                  6.0
              3                                                  2.0
              4                                                  1.0
              ..                                                 ...
              197                                                1.0
              198                                                1.0
              199                                                4.0
              200                                                2.0
              201                                                1.0

                   How many times in the last week did you do the following? - Buy lunch at workplace (e.g., cafeteria)  \
              0                                                  1.0
              1                                                  2.0
              2                                                  NaN
              3                                                  1.0
              4                                                  2.0
              ..                                                 ...
              197                                                1.0
              198                                                3.0
              199                                                1.0
              200                                                1.0
              201                                                1.0

                   How many times in the last week did you do the following? - Buy lunch at a restaurant / food court / food truck  \
              0                                                  4.0
              1                                                  4.0
              2                                                  NaN
              3                                                  6.0
              4                                                  2.0
              ..                                                 ...
              197                                                3.0
              198                                                3.0
              199                                                2.0
              200                                                1.0
              201                                                3.0

                   How many times in the last week did you do the following? - Skipped lunch / ate a small snack item  \
              0                                                  1.0
              1                                                  2.0
              2                                                  NaN
              3                                                  1.0
              4                                                  1.0
              ..                                                 ...
              197                                                1.0
              198                                                2.0
              199                                                1.0
              200                                                1.0
              201                                                1.0

                  How many times in the last week did you do the following? - Other (please specify):  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  NaN
              4                                                  NaN
              ..                                                 ...
              197                                                NaN
              198                                                NaN
              199                                                NaN
              200                                                NaN
              201                                                NaN

                  Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Most frequent  \
              0                                    sticks kebab shop
              1                                        Everyday Cafe
              2                                             Chipotle
              3                                             Chipotle
              4                                               Panera
              ..                                                 ...
              197                                        Chick fil a
              198                                             Sticks
              199                                    Mona Lisa Pizza
              200                                          Chic fila
              201                                              Moe's

                  Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Second most frequent  \
              0                                               panera
              1                                           Christians
              2                                               Sticks
              3                                               Sticks
              4                                          Chick Fil A
              ..                                                 ...
              197                                             Sticks
              198                                          Applebees
              199                                             Panera
              200                                           Chipotle
              201                                          Chic fila

                  Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Third most frequent  \
              0                                            starbucks
              1                                               Sticks
              2                                          Osaka Sushi
              3                                       Noodles and co
              4                                              Champps
              ..                                                 ...
              197                                            Chinese
              198                                        Red Lobster
              199                                           Chipotle
              200                                             Panera
              201                                            Wendy's

                   ...  \
              0    ...
              1    ...
              2    ...
              3    ...
              4    ...
              ..   ...
              197  ...
              198  ...
              199  ...
              200  ...
              201  ...

                  In what activities or hobbies do you participate yourself? - Kid's activities  \
              0                                                  NaN
              1                                                 17.0
              2                                                  NaN
              3                                                  NaN
              4                                                 17.0
              ..                                                 ...
              197                                               17.0
              198                                                NaN
              199                                                NaN
              200                                                NaN
              201                                               17.0

                  In what activities or hobbies do you participate yourself? - Other (please specify)  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  NaN
              4                                                  NaN
              ..                                                 ...
              197                                                NaN
              198                                                NaN
              199                                                NaN
              200                                                NaN
              201                                                NaN

                   In the last month, how many times have you used coupons when you visited a restaurant?  \
              0                                                  1.0
              1                                                  2.0
              2                                                  1.0
              3                                                  4.0
              4                                                  3.0
              ..                                                 ...
              197                                                1.0
              198                                                2.0
              199                                                1.0
              200                                                2.0
              201                                                4.0

                   How do you find restaurant coupons?  Please check all that apply. - Valpak or other direct mail items  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  NaN
              4                                                  1.0
              ..                                                 ...
              197                                                NaN
              198                                                1.0
              199                                                NaN
              200                                                NaN
              201                                                1.0

                   How do you find restaurant coupons?  Please check all that apply. - Coupon from coupon site or blog ( e.g., print at home)  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  2.0
              4                                                  NaN
              ..                                                 ...
              197                                                NaN
              198                                                2.0
              199                                                NaN
              200                                                NaN
              201                                                NaN

                   How do you find restaurant coupons?  Please check all that apply. - Groupon or other social / daily deal offers  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  3.0
              4                                                  3.0
              ..                                                 ...
              197                                                NaN
              198                                                3.0
              199                                                NaN
              200                                                NaN
              201                                                3.0

                   How do you find restaurant coupons?  Please check all that apply. - Store receipt offer ( from previous visit)  \
              0                                                  NaN
              1                                                  NaN
              2                                                  NaN
              3                                                  NaN
              4                                                  4.0
              ..                                                 ...
              197                                                NaN
              198                                                NaN
              199                                                NaN
              200                                                4.0
              201                                                4.0

                   How do you find restaurant coupons?  Please check all that apply. - Loyalty card reward ( e.g., 10th visit free meal)  \
              0                                                  NaN

In [5]:
sheets = list(df.keys())[1:]
df_Sheet1 = df[sheets[0]]
df_Additional_Demo_Codes = df[sheets[1]]
df_Customer_Survey = df[sheets[2]]
df_Noncustomer_Survey = df[sheets[3]]

In [22]:
sheets = list(df.keys())[1:]
df_Sheet1 = df[sheets[0]]
df_Additional_Demo_Codes = df[sheets[1]]
df_Customer_Survey = df[sheets[2]]
df_Noncustomer_Survey = df[sheets[3]]

In [6]:
# 2. Count the number of customers and noncustomers
#  >> 어디 기준으로 봐야 하는지, sheet1에서 count한것과 customder survey랑 다르다

In [7]:
df_Sheet1['Customer'].value_counts()

1    205
0    190
Name: Customer, dtype: int64

In [8]:
# 3. Provide summary statistics (mean, min/max) for these two groups (i.e ., gender, age, income, household type, etc.)

In [9]:
for i in range(len(df_Customer_Survey.columns)):
    print(i, df_Customer_Survey.columns[i])
    
# ['What is your gender?', 'What is your age?', 'What is your approximate average annual household income?']

0 obs
1 How many times in the last week did you do the following? - Make and eat lunch at home
2 How many times in the last week did you do the following? - Bring own lunch to work
3 How many times in the last week did you do the following? - Buy lunch at workplace (e.g., cafeteria)
4 How many times in the last week did you do the following? - Buy lunch at a restaurant / food court / food truck
5 How many times in the last week did you do the following? - Skipped lunch / ate a small snack item
6 How many times in the last week did you do the following? - Other (please specify):
7 Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Most frequent
8 Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Second most frequent
9 Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Third most frequent
10 Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Fourth most frequent
11 Please specify the top five restaurants you have visited in the last six months in order of visit frequency.      - Fifth most frequent
12 Have you ever visited Sticks Kebob Shop?
13 How did you first find out about Sticks? - Heard from a friend or colleague
14 How did you first find out about Sticks? - Saw in media ( print or online-Facebook, blog, review)
15 How did you first find out about Sticks? - Direct marketing ( e.g., Valpak, Groupon)
16 How did you first find out about Sticks? - Noticed while driving or walking by restaurant
17 How did you first find out about Sticks? - Noticed from catering at workplace ( e.g., menu stack)
18 How did you first find out about Sticks? - Noticed at outdoor event / food festival
19 How did you first find out about Sticks? - Other (please specify)
20 Have you eaten at Sticks in the past three months?
21 In the last month, how often have you visited Sticks for the following occasions? - Weekday lunch
22 In the last month, how often have you visited Sticks for the following occasions? - Weekday dinner
23 In the last month, how often have you visited Sticks for the following occasions? - Weekend lunch
24 In the last month, how often have you visited Sticks for the following occasions? - Weekend dinner
25 In the last month, how often have you visited Sticks for the following occasions? - Sticks event ( catering at work, food festival)
26 In the last month, how often have you visited Sticks for the following occasions? - After school snack or after sports practice / event
27 In the last month, how often have you visited Sticks for the following occasions? - Other (please specify)
28 Please indicate how important the following factors are when you visit a restaurant  - Convenient place to eat
29 Please indicate how important the following factors are when you visit a restaurant  - Variety of menu options
30 Please indicate how important the following factors are when you visit a restaurant  - Good value for money
31 Please indicate how important the following factors are when you visit a restaurant  - Healthy menu options
32 Please indicate how important the following factors are when you visit a restaurant  - Food taste and satisfaction
33 Please indicate how important the following factors are when you visit a restaurant  - Friendly staff
34 Please indicate how important the following factors are when you visit a restaurant  - Pleasant ambiance
35 Please indicate how important the following factors are when you visit a restaurant  - Consistency / reliability
36 Please indicate how important the following factors are when you visit a restaurant  - Part of community
37 Please indicate how important the following factors are when you visit a restaurant  - Other (please specify)
38 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Convenient place to eat
39 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Variety of menu options
40 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Good value for money
41 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Healthy menu options
42 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Food taste and satisfaction
43 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Friendly staff
44 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Pleasant ambiance
45 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Consistency / reliability
46 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Part of community
47 Please indicate how you rate Sticks in comparison to similar restaurants that you visit regularly  - Other (please specify)
48 What is your gender?
49 What is your age?
50 What is your approximate average annual household income?
51 How would you best describe your household type?
52 How many children, by age, currently live in your household? - less than 12 years old
53 How many children, by age, currently live in your household? - 12-17 years old
54 How many children, by age, currently live in your household? - 18 and older
55 Please indicate your best answers to the following: - I tend to plan things very carefully
56 Please indicate your best answers to the following: - I sometimes have trouble controlling my spending
57 Please indicate your best answers to the following: - I think it is important to purchase products that are made locally
58 Please indicate your best answers to the following: - I carefully consider the health benefits of what I eat
59 Please indicate your best answers to the following: - Comments:
60 What is your profession? - Accountant
61 What is your profession? - Lawyer
62 What is your profession? - General purpose contractor
63 What is your profession? - Design
64 What is your profession? - Educator
65 What is your profession? - Homemaker
66 What is your profession? - Business professional
67 What is your profession? - Other (please specify)
68 If you have children living at home, in what activities do they participate?  Please check all that apply. - Soccer
69 If you have children living at home, in what activities do they participate?  Please check all that apply. - Football
70 If you have children living at home, in what activities do they participate?  Please check all that apply. - Tennis
71 If you have children living at home, in what activities do they participate?  Please check all that apply. - Lacrosse
72 If you have children living at home, in what activities do they participate?  Please check all that apply. - Swimming
73 If you have children living at home, in what activities do they participate?  Please check all that apply. - Music
74 If you have children living at home, in what activities do they participate?  Please check all that apply. - Hiking
75 If you have children living at home, in what activities do they participate?  Please check all that apply. - Visiting local attractions
76 If you have children living at home, in what activities do they participate?  Please check all that apply. - Visiting children's museums
77 If you have children living at home, in what activities do they participate?  Please check all that apply. - Attending local sporting events
78 If you have children living at home, in what activities do they participate?  Please check all that apply. - Other (please specify)
79 In what activities or hobbies do you participate yourself? - Volunteer work
80 In what activities or hobbies do you participate yourself? - Tennis
81 In what activities or hobbies do you participate yourself? - Swimming
82 In what activities or hobbies do you participate yourself? - Skiing / snow boarding
83 In what activities or hobbies do you participate yourself? - Running
84 In what activities or hobbies do you participate yourself? - Hiking
85 In what activities or hobbies do you participate yourself? - Golf
86 In what activities or hobbies do you participate yourself? - Gardening
87 In what activities or hobbies do you participate yourself? - Fishing
88 In what activities or hobbies do you participate yourself? - Camping
89 In what activities or hobbies do you participate yourself? - Bicycling
90 In what activities or hobbies do you participate yourself? - Yoga
91 In what activities or hobbies do you participate yourself? - Book clubs
92 In what activities or hobbies do you participate yourself? - Eating out
93 In what activities or hobbies do you participate yourself? - Attending local sports events
94 In what activities or hobbies do you participate yourself? - Visiting museums
95 In what activities or hobbies do you participate yourself? - Kid's activities
96 In what activities or hobbies do you participate yourself? - Other (please specify)
97 In the last month, how many times have you used coupons when you visited a restaurant?
98 How do you find restaurant coupons?  Please check all that apply. - Valpak or other direct mail items
99 How do you find restaurant coupons?  Please check all that apply. - Coupon from coupon site or blog ( e.g., print at home)
100 How do you find restaurant coupons?  Please check all that apply. - Groupon or other social / daily deal offers
101 How do you find restaurant coupons?  Please check all that apply. - Store receipt offer ( from previous visit)
102 How do you find restaurant coupons?  Please check all that apply. - Loyalty card reward ( e.g., 10th visit free meal)
103 How do you find restaurant coupons?  Please check all that apply. - Offers mentioned in media: radio, tv, newspaper, etc.
104 How do you find restaurant coupons?  Please check all that apply. - Other (please specify)

In [10]:
df_Customer_Survey.iloc[:, [48, 49, 50]].describe()
# 그냥 이렇게 구하면 안된다 이걸 어떻게 변환할건지 얘기해봐야함 

# genders는 범주형 변수고, age는 순서형 변수여서.... 맞는건지 잘 모르겠음

,What is your gender?,What is your age?,What is your approximate average annual household income?
count,195.00000,195.000000,195.000000
mean,1.20000,2.374359,1.984615
std,0.40103,0.765465,0.763044
min,1.00000,1.000000,1.000000
25%,1.00000,2.000000,1.000000
50%,1.00000,2.000000,2.000000
75%,1.00000,3.000000,3.000000
max,2.00000,4.000000,3.000000

In [11]:
# 4. Cross-tab with Chi-square test (between categorical variables)
# • Is there a relation between customer membership and age groups?
# • Is there a relation between customer membership and income groups?
# Please state the null hypothesis (H0) and test whether to reject or fail to reject H0.

In [12]:
from scipy.stats import chi2_contingency
# Is there a relation between customer membership and age groups?
# H0:회원과 나이그룹은 서로 관계가 없다
# H1:회원과 나이그룹은 서로 관계가 있다

In [13]:
df_q4_mem = df_Customer_Survey['What is your age?'].to_frame()
df_q4_nonmem = df_Noncustomer_Survey['What is your age?'].to_frame()

In [14]:
df_q4_mem.loc[:, 'membership_yn'] = 1
df_q4_nonmem.loc[:, 'membership_yn'] = 0

In [15]:
df_q4 =pd.concat([df_q4_mem, df_q4_nonmem], axis = 0)

In [16]:
df_q4

     What is your age?  membership_yn
0                  3.0              1
1                  2.0              1
2                  2.0              1
3                  2.0              1
4                  3.0              1
..                 ...            ...
187                3.0              0
188                3.0              0
189                2.0              0
190                NaN              0
191                NaN              0

[394 rows x 2 columns]

In [17]:
print(df_q4_mem.shape)
print(df_q4_nonmem.shape)

(202, 2)
(192, 2)

In [18]:
df_q4_mem.columns

Index(['What is your age?', 'membership_yn'], dtype='object')

In [19]:
df_q4.dropna(inplace=True)

In [20]:
df_q4

     What is your age?  membership_yn
0                  3.0              1
1                  2.0              1
2                  2.0              1
3                  2.0              1
4                  3.0              1
..                 ...            ...
184                3.0              0
186                1.0              0
187                3.0              0
188                3.0              0
189                2.0              0

[345 rows x 2 columns]

In [21]:
df_q4_1 = pd.crosstab(df_q4['What is your age?'], df_q4['membership_yn'])

In [ ]:
# p-value : 0.05보다 작으므로 귀무가설 기각
chi2_contingency(df_q4_1)[1]

In [ ]:
# • Is there a relation between customer membership and income groups?

# What is your approximate average annual household income?

In [ ]:
df_q4_mem = df_Customer_Survey['What is your approximate average annual household income?'].to_frame()
df_q4_nonmem = df_Noncustomer_Survey['What is your approximate average annual household income?'].to_frame()

In [ ]:
df_q4_mem.loc[:, 'membership_yn'] = 1
df_q4_nonmem.loc[:, 'membership_yn'] = 0

In [ ]:
df_q4 =pd.concat([df_q4_mem, df_q4_nonmem], axis = 0)

In [ ]:
print(df_q4_mem.shape)
print(df_q4_nonmem.shape)

In [ ]:
df_q4.dropna(inplace=True)

In [ ]:
df_q4

In [ ]:
df_q4_2 = pd.crosstab(df_q4['What is your approximate average annual household income?'], df_q4['membership_yn'])

In [ ]:
# p-value : 0.05보다 작으므로 귀무가설 기각
format(chi2_contingency(df_q4_2)[1], '.8f')

In [ ]:
# 5 Independent Sample T-test (2 groups):
# • Check the statistical difference between customers and noncustomers for Q 16-a,b,c,d
# age 가 null인거 날림
# H0 : 두 집단의 평균이 같다
# H1 : 두 집단의 평균이 다르다

In [ ]:
df_q5_nonmem = df_Sheet1.loc[df_Sheet1['Customer']==0]
df_q5_mem = df_Sheet1.loc[df_Sheet1['Customer']==1]

In [ ]:
df_q5_nonmem = df_q5_nonmem.iloc[:, [2,3,4,5] ]
df_q5_mem = df_q5_mem.iloc[:, [2,3,4,5] ]

In [ ]:
import scipy.stats

scipy.stats.ttest_ind(df_q5_nonmem, df_q5_mem, equal_var=False)

In [ ]:
# 6. ANOVA (more than 2 independent groups)
# Check the statistical difference across the four different age groups for 16-a,b,c,d

In [ ]:
df_q6_1 = pd.merge(df_Sheet1, df_Customer_Survey.loc[:, ['obs', 'What is your age?']], left_on = 'Obs', right_on = 'obs', how='left').drop(columns='obs')

In [ ]:
df_q6_2 = pd.merge(df_q6_1, df_Noncustomer_Survey.loc[:, ['obs', 'What is your age?']], left_on = 'Obs', right_on = 'obs', how='left').drop(columns='obs')

In [ ]:
df_q6_2['age_grp'] = np.where(df_q6_2['What is your age?_x'].isna(), df_q6_2['What is your age?_y'], df_q6_2['What is your age?_x'])

In [ ]:
df_q6_3 = df_q6_2.iloc[:, [2,3,4,5,9]]

In [ ]:
df_q6_3.dropna(inplace=True)

In [ ]:
df_q6_3.shape

In [ ]:
np.unique(df_q6_3.age_grp)

In [ ]:
df_q6_3.columns[2]

In [ ]:
df_q6_grp1 = df_q6_3.loc[df_q6_3.age_grp==1, df_q6_3.columns[2]]
df_q6_grp2 = df_q6_3.loc[df_q6_3.age_grp==2, df_q6_3.columns[2]]
df_q6_grp3 = df_q6_3.loc[df_q6_3.age_grp==3, df_q6_3.columns[2]]
df_q6_grp4 = df_q6_3.loc[df_q6_3.age_grp==4, df_q6_3.columns[2]]

In [ ]:
import scipy.stats as stats

stats.f_oneway(df_q6_grp1, df_q6_grp2, df_q6_grp3, df_q6_grp4)

In [ ]:
df_q6_grp1 = df_q6_3.loc[df_q6_3.age_grp==1, df_q6_3.columns[3]]
df_q6_grp2 = df_q6_3.loc[df_q6_3.age_grp==2, df_q6_3.columns[3]]
df_q6_grp3 = df_q6_3.loc[df_q6_3.age_grp==3, df_q6_3.columns[3]]
df_q6_grp4 = df_q6_3.loc[df_q6_3.age_grp==4, df_q6_3.columns[3]]

In [ ]:
import scipy.stats as stats

stats.f_oneway(df_q6_grp1, df_q6_grp2, df_q6_grp3, df_q6_grp4)

In [ ]:
# 7. Use responses in Q16-a,b,c,d & Run k-means clustering algorithm

In [ ]:
df_q6 = df_Sheet1.copy()
df_q6.dropna(inplace=True)

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

inertia_list = []
silhouette_list = []
kmeans_per_k = []

# grid search를 통해 클러스터 개수 바꾸어가며 결과 확인 
cluster_num = range(2, 15)
for i in cluster_num:
    
    # 그룹 수, random_state 설정
    model = KMeans(n_clusters = i, random_state = 10)

    # 정규화된 데이터에 학습
    model.fit(df_q6.iloc[:,[2,3,4,5]])

    # 클러스터링 결과 각 데이터가 몇 번째 그룹에 속하는지 저장
    df_q6['cluster'] = model.fit_predict(df_q6.iloc[:,[2,3,4,5]])
    
    # 클러스터 개수 별 이너셔 값 확인을 위해 데이터 저장 
    inertia_list = np.append(inertia_list, model.inertia_)
    # 클러스터 개수 별 실루엣 값 확인을 위해 데이터 저장 
    silhouette_list = np.append(silhouette_list, silhouette_score(df_q6.iloc[:,[2,3,4,5]], model.labels_))
    # 추후 모델 재사용을 위해 모델 저장
    kmeans_per_k.append(model)

In [ ]:
# 8.Show your elbow plot & Determine the number of segments for your analysis

In [ ]:
# 맥북 그래프 출력 시 한글 깨짐 현상으로 코드 추가 
from matplotlib import rc
import platform 

if platform.system()=='Darwin' : 
    rc('font', family='AppleGothic')
    plt.rcParams['axes.unicode_minus'] = False

In [ ]:
import matplotlib.pyplot as plt
# https://matplotlib.org/3.5.0/tutorials/colors/colormaps.html
# 실루엣 점수 시각화
## 엘보 지점이 가장 좋은데 뚜렷하게 보이지 않아 실루엣 계수 확인 진행 
plt.plot(cluster_num, inertia_list, color = '#008000')
plt.title('클러스터 개수 별 이너셔 점수 시각화')
plt.show()

# 실루엣계수 그래프
# 1에 가까울수록 좋은 모델인데, 갈수록 낮아짐
# 3 혹은 5 가 좋은 클러스터 개수일것으로 보임
# 추가적으로 실루엣 그래프 확인
plt.plot(cluster_num, silhouette_list, color = '#008000')
plt.xticks(np.arange(2, 15))
plt.axvline(x=3, color='r', linestyle='--', linewidth=2)
plt.axvline(x=5, color='r', linestyle='--', linewidth=2)
plt.title('클러스터 개수 별 실루엣 계수 시각화')
plt.show()